package shell

import (
	"fmt"
	"regexp"
	"strings"
)

// --- Zsh quoting ---

func shellQuote(value string) string {
	return "'" + strings.ReplaceAll(value, "'", `'\''`) + "'"
}

func shellWord(value string) string {
	if regexp.MustCompile(`^[A-Za-z0-9_./:=+-]+$`).MatchString(value) {
		return value
	}
	return shellQuote(value)
}

func zshCommandWords(values []string) []string {
	out := make([]string, 0, len(values))
	for _, value := range values {
		out = append(out, shellQuote(value))
	}
	return out
}

// --- Zsh rendering ---

// RenderManagedZsh renders the wrenyard.zsh managed shell file for the given
// profiles. Profiles are keyed by profile name. funcNames determines the
// ordering and selection. credResolver and managedProvider are callbacks
// that let the root package inject its credential resolution without the
// shell package importing the root forge package.
func RenderManagedZsh(
	profiles map[string]Profile,
	funcNames []string,
	credResolver func(string) (string, bool),
	managedProvider func(string) bool,
) (string, error) {
	var b strings.Builder
	b.WriteString("# Generated by Wrenyard. Do not edit; run `wrenyard runtime setup` to refresh.\n")
	for _, name := range funcNames {
		p, ok := profiles[name]
		if !ok {
			continue
		}
		if isRawClaudeAliasProfile(p) {
			b.WriteString(renderZshRawClaudeAliasProfile(name, p))
			continue
		}
		if providerSupportsCCShortcut(p.Provider) {
			if rendered, err := renderZshDirectClaudeProfile(name, p, credResolver, managedProvider); err == nil {
				b.WriteString(rendered)
			}
			continue
		}
		b.WriteString(renderZshRawClaudeAliasProfile(name, p))
	}
	return b.String(), nil
}

func renderZshRawClaudeAliasProfile(name string, p Profile) string {
	command := claudeShortcutCommand(p)
	var b strings.Builder
	b.WriteString(name)
	b.WriteString("() {\n")
	b.WriteString("  command ")
	b.WriteString(strings.Join(zshCommandWords(command), " "))
	b.WriteString(" \"$@\"\n")
	b.WriteString("}\n\n")
	return b.String()
}

func renderZshDirectClaudeProfile(
	name string,
	p Profile,
	credResolver func(string) (string, bool),
	managedProvider func(string) bool,
) (string, error) {
	p.Name = nonEmpty(p.Name, name)
	command := claudeShortcutCommand(p)

	apiKey := p.Env["ANTHROPIC_API_KEY"]
	// SecretRef resolution is handled by the root facade; the shell
	// package only performs provider-based credential resolution.
	if p.Provider != "" {
		cred, ok := credResolver(p.Provider)
		if !ok || cred == "" {
			if managedProvider(p.Provider) {
				return "", fmt.Errorf("no credential for provider %q; run wrenyard providers auth login %s", p.Provider, p.Provider)
			}
		} else {
			apiKey = cred
		}
	}

	shellEnv := directClaudeEnv(p, apiKey)
	settingsEnv := directClaudeSettingsEnv(p, apiKey)
	settingsJSON := claudeSettingsJSON(p, settingsEnv)

	var b strings.Builder
	b.WriteString(name)
	b.WriteString("() {\n")
	b.WriteString("  local forge_runtime_root=\"${XDG_DATA_HOME:-$HOME/.local/share}/wrenyard/runtime\"\n")
	b.WriteString("  local forge_claude_root=\"$forge_runtime_root/claude/shell-cc\"\n")
	b.WriteString("  local forge_claude_config_dir=\"$forge_claude_root/config\"\n")
	b.WriteString("  local forge_claude_job_dir=\"$forge_claude_root/jobs\"\n")
	b.WriteString("  local forge_claude_settings=\"$forge_claude_config_dir/settings.json\"\n")
	b.WriteString("  mkdir -p \"$forge_claude_config_dir\" \"$forge_claude_job_dir\"\n")
	b.WriteString("  local forge_claude_settings_patch=")
	b.WriteString(shellQuote(settingsJSON))
	b.WriteString("\n")
	b.WriteString("  if ! FORGE_SETTINGS_PATH=\"$forge_claude_settings\" FORGE_SETTINGS_PATCH=\"$forge_claude_settings_patch\" command node -e ")
	b.WriteString(shellQuote(claudeSettingsMergeScript()))
	b.WriteString("; then\n")
	b.WriteString("    printf '%s\\n' \"$forge_claude_settings_patch\" > \"$forge_claude_settings\"\n")
	b.WriteString("  fi\n")
	b.WriteString(renderZshClaudeCleanStart())
	b.WriteString("  local forge_project_settings=\"$PWD/.claude/settings.json\"\n")
	b.WriteString("  local -a forge_profile_args\n")
	b.WriteString("  forge_profile_args=()\n")
	b.WriteString("  if [[ -f \"$forge_project_settings\" ]]; then\n")
	b.WriteString("    forge_profile_args+=(--settings \"$forge_project_settings\")\n")
	b.WriteString("  fi\n")
	b.WriteString("  env -u ANTHROPIC_AUTH_TOKEN \\\n")
	b.WriteString("    -u ANTHROPIC_BASE_URL \\\n")
	b.WriteString("    -u ANTHROPIC_API_KEY \\\n")
	b.WriteString("    CLAUDE_CONFIG_DIR=\"$forge_claude_config_dir\" \\\n")
	b.WriteString("    CLAUDE_JOB_DIR=\"$forge_claude_job_dir\" \\\n")
	for _, key := range sortedStringKeys(shellEnv) {
		b.WriteString("    ")
		b.WriteString(key)
		b.WriteString("=")
		b.WriteString(shellQuote(shellEnv[key]))
		b.WriteString(" \\\n")
	}
	b.WriteString("    ")
	b.WriteString("command wrenyard runtime shell exec ")
	b.WriteString(shellQuote(p.Name))
	b.WriteString(" -- ")
	b.WriteString(strings.Join(zshCommandWords(command), " "))
	b.WriteString(" \"${forge_profile_args[@]}\" \"$@\"\n")
	b.WriteString("}\n\n")
	return b.String(), nil
}

func renderZshClaudeCleanStart() string {
	var b strings.Builder
	b.WriteString("  CLAUDE_CONFIG_DIR=\"$forge_claude_config_dir\" command claude daemon stop --any >/dev/null 2>&1 || true\n")
	b.WriteString("  if command -v pgrep >/dev/null 2>&1; then\n")
	b.WriteString("    local forge_pid\n")
	b.WriteString("    while IFS= read -r forge_pid; do\n")
	b.WriteString("      [[ -z \"$forge_pid\" || \"$forge_pid\" == \"$$\" ]] && continue\n")
	b.WriteString("      kill \"$forge_pid\" >/dev/null 2>&1 || true\n")
	b.WriteString("    done < <(pgrep -f '(^|[/\\\\])claude([ ._-]|$)|@anthropic-ai[/\\\\]claude-code' 2>/dev/null)\n")
	b.WriteString("    sleep 0.25\n")
	b.WriteString("    while IFS= read -r forge_pid; do\n")
	b.WriteString("      [[ -z \"$forge_pid\" || \"$forge_pid\" == \"$$\" ]] && continue\n")
	b.WriteString("      kill -9 \"$forge_pid\" >/dev/null 2>&1 || true\n")
	b.WriteString("    done < <(pgrep -f '(^|[/\\\\])claude([ ._-]|$)|@anthropic-ai[/\\\\]claude-code' 2>/dev/null)\n")
	b.WriteString("  fi\n")
	return b.String()
}

// --- policy helpers embedded in the shell package ---
// (These are duplicated from root so the shell package can make rendering
// decisions without importing the root forge package.)

var ccShortcutProviders = map[string]bool{
	"zhipu-coding": true,
	"kimi-coding":  true,
	"deepseek":     true,
}

func providerSupportsCCShortcut(provider string) bool {
	return ccShortcutProviders[provider]
}

func isRawClaudeAliasProfile(p Profile) bool {
	return p.Provider == "anthropic"
}
