package shell

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/wrenyard/wrenyard/runtime/forge/internal/lifecycle/layout"
)

func TestPlanZshRetirementRemovesOnlyOwnedIntegration(t *testing.T) {
	home := t.TempDir()
	t.Setenv("XDG_CONFIG_HOME", "")
	managed := filepath.Join(layout.NewPaths(home).ConfigDir(), "shell", "wrenyard.zsh")
	canonical := "# generated by Wrenyard\n"
	if err := os.MkdirAll(filepath.Dir(managed), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(managed, []byte(canonical), 0o644); err != nil {
		t.Fatal(err)
	}
	zshrc := filepath.Join(home, ".zshrc")
	profile := "export FOREIGN_SETTING=keep\n\n" + blockStartZsh + "\n" + blockLineZsh + "\n" + blockEndZsh + "\n"
	if err := os.WriteFile(zshrc, []byte(profile), 0o644); err != nil {
		t.Fatal(err)
	}
	legacyData := filepath.Join(home, ".config", "wrenyard", "runtime", "shell-cc", "retained.json")
	if err := os.MkdirAll(filepath.Dir(legacyData), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(legacyData, []byte("retained\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	plan := PlanZshRetirement(home, canonical)
	if plan.DriftedManagedFile {
		t.Fatal("byte-identical managed file must not be reported as drifted")
	}
	if len(plan.ChangePlan.Actions) != 2 {
		t.Fatalf("actions=%d, want profile write plus managed file delete", len(plan.ChangePlan.Actions))
	}
	if plan.ChangePlan.Actions[0].Type != "file_write" || plan.ChangePlan.Actions[0].File.Content != "export FOREIGN_SETTING=keep\n" {
		t.Fatalf("unexpected profile retirement action: %#v", plan.ChangePlan.Actions[0])
	}
	if plan.ChangePlan.Actions[1].Type != "file_delete" || plan.ChangePlan.Actions[1].File.Path != managed {
		t.Fatalf("unexpected managed file retirement action: %#v", plan.ChangePlan.Actions[1])
	}
	if _, err := os.Stat(legacyData); err != nil {
		t.Fatalf("planning must leave isolated client data untouched: %v", err)
	}
}

func TestPlanZshRetirementRetainsDriftedManagedFile(t *testing.T) {
	home := t.TempDir()
	t.Setenv("XDG_CONFIG_HOME", "")
	managed := filepath.Join(layout.NewPaths(home).ConfigDir(), "shell", "wrenyard.zsh")
	if err := os.MkdirAll(filepath.Dir(managed), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(managed, []byte("# user changed this file\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	plan := PlanZshRetirement(home, "# generated by Wrenyard\n")
	if !plan.DriftedManagedFile {
		t.Fatal("drifted managed file should be retained and reported")
	}
	if len(plan.ChangePlan.Actions) != 0 {
		t.Fatalf("drifted file without profile block should not be mutated: %#v", plan.ChangePlan.Actions)
	}
}
