export type RuntimeOperationName = 'agent' | 'shell'
export type DomainOperationName = 'task'
export type ControlOperationName = 'checkpoint'
export type OperationName = DomainOperationName | RuntimeOperationName | ControlOperationName

export type OperationKind = 'domain' | 'runtime' | 'control'

export interface OperationDescriptor {
  name: OperationName
  kind: OperationKind
  description: string
}

export type ClientFamily = 'claude' | 'codex' | 'opencode' | 'cursor' | 'grok' | 'dsh' | 'codebuddy'

/**
 * Private, non-persistent CodeBuddy admission binding captured from one active
 * credential snapshot. It is deliberately separate from TaskDispatchSnapshot:
 * these values may reach only the local client admission process environment
 * and must never enter telemetry, protocol DTOs, logs, or database rows.
 */
export interface CodeBuddyExecutionBinding {
  readonly expectedScope: string
  readonly expectedEnvironment: string
  readonly expectedWireModel: string
}

/**
 * Per-attempt dispatch snapshot captured by the daemon resolver before the first
 * agent execution. This is now the exact shared `TaskResolvedDispatch` attempt
 * snapshot produced by `@wrenyard/auto-routing`'s resolver and persisted by the
 * supervisor into `task_run_attempt_dispatch` — carrying the full
 * client/provider/model/model_id/mode/protocol, speed evidence, intelligence,
 * and reference pricing. The execution id is generated by the supervisor and is
 * intentionally NOT part of the pre-launch snapshot type.
 */
import type { TaskResolvedDispatch } from '../../task-run-metadata-types.mts'

export type TaskDispatchSnapshot = TaskResolvedDispatch

import type { AgentFailureClass } from '../task/failure.mts'
export type ExecutionStatus =
  | 'queued'
  | 'starting'
  | 'running'
  | 'done'
  | 'failed'
  | 'cancelled'
  | 'timeout'
  | 'interrupted'

export interface StartAgentExecutionOptions {
  taskId?: string
  profile: string
  /** Repository coordination only: when true this execution participates in
   *  Foreman's repo write-lock admission. There is no permission concept any
   *  more; every client always launches in its unrestricted runtime mode. */
  repoWriteLock?: boolean
  cwd: string
  prompt: string
  resume?: string
  timeoutMs?: number
  clientFamily?: ClientFamily
  /** Normalized agent runtime string ('<runtime>/<config-id>') carried from the
   *  task definition. Null for historical/legacy executions that predate this field. */
  requestedAgentRuntime?: string
  /** Selected execution-feature ids (MCP feature bundles) carried from the task
   *  definition. Lowered to exec feature ids by an explicit name map before an
   *  execution starts; an unmapped id throws rather than being dropped. */
  features?: readonly string[]
  /** Canonical exact file paths for file-scoped write admission. Empty retains
   *  conservative repo-wide locking when repoWriteLock is true. */
  writePaths?: readonly string[]
  /** Per-attempt dispatch snapshot produced by the daemon resolver. Persisted
   *  by the supervisor keyed by execution_id/task_id. */
  dispatchSnapshot?: TaskDispatchSnapshot | null
  /** Private CodeBuddy admission binding; kept in memory only. */
  codeBuddyExecution?: CodeBuddyExecutionBinding
  /** Canonical agent-runtime failure class, when supplied by the resolver. */
  failureClass?: AgentFailureClass | string | null
}

export interface ExecutionResult {
  executionId: string
  status: ExecutionStatus
  output?: string | null
  error?: string | null
  exitCode?: number | null
  killReason?: string | null
  /** Canonical agent-runtime failure class captured from `run_finished`, if present. */
  failureClass?: AgentFailureClass | string | null
}

export interface ExecutionHandle {
  executionId: string
  pid?: number
  wait(): Promise<ExecutionResult>
  cancel(): Promise<void>
}

/**
 * Live execution row. The persisted `executions.permission` column is INERT DB
 * legacy: it is written as a fixed literal for schema compatibility and never
 * read or interpreted, so it deliberately has no field here.
 */
export interface ExecutionRecord {
  id: string
  task_id: string | null
  profile: string
  cwd: string
  prompt: string
  status: ExecutionStatus
  native_session_id: string | null
  client_family: ClientFamily | null
  pid: number | null
  pgid: number | null
  output: string | null
  raw_result: string | null
  error: string | null
  exit_code: number | null
  kill_reason: string | null
  timeout_ms: number | null
  requested_agent_runtime?: string | null
  resolved_profile?: string | null
  /** Canonical agent-runtime failure class captured from `run_finished`, if present. */
  failure_class?: string | null
}

export interface AgentExecutionHost {
  startExecution(opts: StartAgentExecutionOptions): Promise<ExecutionHandle>
  waitExecution(executionId: string): Promise<ExecutionResult>
  getExecution(executionId: string): ExecutionRecord | undefined
  cancelExecution(executionId: string): Promise<void>
}

export interface TaskRunAcceptedHandle {
  id: string
  task_run_id: string
  hint: string
}

export interface StartTaskRunOptions {
  definitionName: string
  taskName: string
  project: string
  executionProject: string
  input: unknown
  workspaceRoot: string
  workingDirectory: string
  worktree?: string
  connectingId?: string
  /** Bounded JSON-safe context injected separately from definition input. */
  taskContext?: import('../task/context.mts').TaskContext
  /** Authoritative resolved definition provenance. Absent for legacy/direct
   *  callers that predate source threading; never guessed from project/id. */
  source?: 'builtin' | 'project'
  /** Non-persistent public snake_case invocation settings layer for this run
   *  only. Sits at the top of the field precedence chain and is never
   *  persisted by the daemon. */
  invocationSettings?: import('../../protocol/methods/task.mts').TaskSettingsLayer
}

export interface TaskWorkflowRunHost {
  startTaskRun(opts: StartTaskRunOptions): Promise<TaskRunAcceptedHandle>
  cancelTaskRun(taskRunId: string): Promise<Record<string, unknown>>
}

export interface OperationHost {
  agent?: AgentExecutionHost
  runner?: TaskWorkflowRunHost
}
